### ISSUE TITLE
Implementation of serial 3D model

### ISSUE THREAD

**Issue by matt-frey** [matt-frey/epic#230]
- [x] eigenvalue solver + unit test (see #229)
- [x] ellipsoid module (see #233)
- [x] unit tests 
    * [x] par2grid (see #242)
    * [x] grid2par (see #246)
    * [x] reflective BC (see #246)
    * [x] free slip BC (see #246)
- [x] ~generalisation of dimension (see #227)~
- [x] parcel splitting + unit test (see #237)
- [x] 3D nearest routine and parcel merging + unit tests (see #243)
- [x] parcel initialisation + unit test (see #238)
- [x] parcel correction + unit tests (see #241)
- [x] FFT solver
  * [x] 2D FFT (see #240)
  * [x] vor2vel + unit test (see #247)
  * [x] vorticity tendency + unit test (see #248 and #249)
- [x] OpenMP parallel stafft.f90 (see #239)
- [x] adaptive time step estimate (see #250)
- [x] update RK4 (see #244)
